language: java
services:
  - mysql
jdk:
 - oraclejdk8
cache:
  directories:
   - $HOME/.m2

before_install:
  - mysql -e 'CREATE USER 'j4mt'@'localhost' IDENTIFIED BY 'P@ssw0rd';'
  - mysql -e 'GRANT ALL PRIVILEGES ON * . * TO 'j4mt'@'localhost';'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS j4mtutil;'

install:
- oss/ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- oss/ mvn test